version: '3'
services:
  seatsaver:
    build: ./
    environment:
      MESSAGE_BROKER_HOST: redis
      MONGODB_URL: http://mongodb:27017
    ports:
      - "4000:4000"
    networks:
      - seatsaver
  mongodb:
    image: mongo
    networks:
      - seatsaver
  redis:
    image: redis
    networks:
      - seatsaver
networks:
  seatsaver: